### ISSUE TITLE
Fail to generate esp8266Interface wrapper

### ISSUE THREAD

**Issue by cyliangtw** [janjongboom/mbed-js-wrapper-generator#1]
1. Created one WiFi example to utilize esp8266 lib and proved DHCP OK
2.  mbed compile -m NUMAKER_PFM_NUC472 -t GCC_ARM --profile ./mbed-os/tools/profiles/debug.json
3. arm-none-eabi-objdump.exe -Wi -g ./BUILD/NUMAKER_PFM_NUC472/GCC_ARM/*.elf > symbols.txt
4. node ../mbed-js-wrapper-generator-master/generate.js ./symbols.txt ESP8266Interface
Then, got result as:
```
ESP8266Interface#~ESP8266Interface
Cannot handle this function
Done C:\ARM_mbed\GCC_Make\mbed-js-wrapper-generator-master\output\jerryscript-mbed-esp8266interface-1488350838857
Do not forget to add 'mbed-js-esp8266interface' to your package.json dependencies
```
However, the wrapper implementation `mbed-js-esp8266interface.cpp` is not correct as below:
```
#ifndef _JERRYSCRIPT_MBED_ESP8266INTERFACE_H
#define _JERRYSCRIPT_MBED_ESP8266INTERFACE_H

#include "jerryscript-mbed-library-registry/wrap_tools.h"

// @todo: add a reference to the ESP8266Interface header here

DECLARE_CLASS_CONSTRUCTOR(ESP8266Interface);
jerry_value_t mbed_js_wrap_native_object(ESP8266Interface* ptr);

#endif // _JERRYSCRIPT_MBED_ESP8266INTERFACE_H
```

**Comment by janjongboom** [comment]
@cyliangtw The functions are declared on WiFiInterface, from which ESP8266Interface inherits. Should probably handle that in the generator, but for now this works:

```
node ../mbed-js-wrapper-generator-master/generate.js ./symbols.txt WiFiInterface
```

Then replace `WiFiInterface` with `ESP8266Interface` in the `.cpp` file.

Keep the ESP8266Interface constructor though from `mbed-js-esp8266interface.cpp`.

**Comment by cyliangtw** [comment]
Thanks, I realize your instructions, this workaround should be working.
However, `ATTACH_CLASS_FUNCTION` macro can't handle Polymorphism, for ex: `connect()` & `connect(p0,p1,p2,p3)`

**Comment by janjongboom** [comment]
@cyliangtw Yep, I'm aware of it. Quick way around it is by manually patching the functions, like I'm doing in [mbed-js-http](https://github.com/janjongboom/mbed-js-http/blob/master/source/mbed-js-httprequest.cpp#L24).

Anyway, it's something that's on my list to fix.

**Comment by cyliangtw** [comment]
Yes, it's a good alternative way.

**Comment by janjongboom** [comment]
FYI, published blog post here: https://developer.mbed.org/blog/entry/Generating-C-wrappers-for-JS-on-mbed/.

Also added function overloading to the generator now.
